apiVersion: delivery.ocm.software/v1alpha1
kind: Configuration
metadata:
  name: incident-management-deploy-configure
  namespace: ocm-system
spec:
  interval: 1m
  sourceRef:
    kind: Localization
    name: podinfo-deployment # this is the podinfo deployment localization
  configRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: config # here we reference the configuration resource
  values:
    serviceAccountName: app-ops