apiVersion: delivery.ocm.software/v1alpha1
kind: Configuration
metadata:
  name: incident-management-deploy-configure
  namespace: ocm-system
spec:
  interval: 1m
  sourceRef:
    kind: Localization
    name: incident-management-localization # this is the podinfo deployment localization
  configRef:
    kind: ComponentVersion
    name: incident-management-app
    resourceRef:
      name: config # here we reference the configuration resource
      version: latest
  values:
    serviceAccountName: air-gapped-reg