apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: incident-management-deployer
  namespace: ocm-system
spec:
  sourceRef:
    kind: Localization
    name: incident-management-localization
  kustomizationTemplate:
    interval: 1m0s
    path: ./
    prune: true
    targetNamespace: default