apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: incident-management-deployer-test
  namespace: ocm-system
spec:
  sourceRef:
    kind: Configuration
    name: incident-management-deploy-configuration
  kustomizationTemplate:
    interval: 1m0s
    path: ./
    prune: true
    targetNamespace: default